server:
  port: 5225
  #address: 192.168.43.71


spring:
  redis:
    host: localhost
    port: 6379
    database: 2
  servlet:
    multipart:
      max-request-size: 2048MB
      max-file-size: 1024MB

logging:
  file:
    name: D:/repos/Log/SelfSchedule/app.log  # 日志文件名和路径
  level:
    root: INFO  # 根日志级别
    org.springframework.web: DEBUG  # 特定包的日志级别
    com.baomidou.mybatisplus: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # 文件日志格式