spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc?rewriteBatchedStatements=true
    username: root
    password:
mybatis-plus:
  mapperLocations: classpath:Mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: SelfSchedule.Entity.Handler